<?php

/*
|--------------------------------------------------------------------------
| Registre des modèles visuels PDF — 120 templates × 20 familles
|--------------------------------------------------------------------------
| Tableau ORDONNÉ : la limite « templates » du forfait (starter 5, pro 30,
| business 100, enterprise illimité) s'applique par array_slice sur cet
| ordre. Chaque clé correspond à une vue resources/views/pdf/templates/{key}.blade.php.
| 6 layouts maîtres dans resources/views/pdf/partials/_lyt-*.blade.php.
| Couleurs : primary / secondary / accent (hex).
*/

return [

    // ══════════════════════════════════════════════════════════════════════
    // ── CORPORATE (10) ────────────────────────────────────────────────────
    // ══════════════════════════════════════════════════════════════════════
    'corporate-classic' => [
        'name'        => 'Corporate Classic',
        'family'      => 'Corporate',
        'description' => 'En-tête blanc avec bordure bleue marine, tableaux professionnels — template universel.',
        'plan_min'    => 'starter',
        'primary'     => '#1B4FA8',
        'secondary'   => '#002D5B',
        'accent'      => '#F0C040',
    ],
    'corporate-dark' => [
        'name'        => 'Corporate Dark',
        'family'      => 'Corporate',
        'description' => 'En-tête ardoise sombre, accent bleu néon — modernité et impact.',
        'plan_min'    => 'pro',
        'primary'     => '#0F172A',
        'secondary'   => '#1E293B',
        'accent'      => '#3B82F6',
    ],
    'corporate-navy' => [
        'name'        => 'Corporate Navy',
        'family'      => 'Corporate',
        'description' => 'Marine profond et or — prestige intemporel pour grandes entreprises.',
        'plan_min'    => 'pro',
        'primary'     => '#002D5B',
        'secondary'   => '#001A38',
        'accent'      => '#C9922A',
    ],
    'corporate-hero' => [
        'name'        => 'Corporate Hero',
        'family'      => 'Corporate',
        'description' => 'Grand bandeau héro bleu acier — fort impact visuel en première lecture.',
        'plan_min'    => 'pro',
        'primary'     => '#1E3A5F',
        'secondary'   => '#0D2137',
        'accent'      => '#F59E0B',
    ],
    'corporate-slate' => [
        'name'        => 'Corporate Slate',
        'family'      => 'Corporate',
        'description' => 'Ardoise neutre avec accent gris-bleu — élégance discrète et professionnelle.',
        'plan_min'    => 'pro',
        'primary'     => '#334155',
        'secondary'   => '#1E293B',
        'accent'      => '#64748B',
    ],
    'corporate-minimal' => [
        'name'        => 'Corporate Minimal',
        'family'      => 'Corporate',
        'description' => 'Version ultra-épurée — typographie seule, zéro fond coloré.',
        'plan_min'    => 'starter',
        'primary'     => '#374151',
        'secondary'   => '#111827',
        'accent'      => '#6366F1',
    ],
    'corporate-royal' => [
        'name'        => 'Corporate Royal',
        'family'      => 'Corporate',
        'description' => 'Fond indigo nuit et or — prestige absolu pour directions générales.',
        'plan_min'    => 'enterprise',
        'primary'     => '#1A1063',
        'secondary'   => '#0D0840',
        'accent'      => '#C9922A',
    ],
    'corporate-green' => [
        'name'        => 'Corporate Green',
        'family'      => 'Corporate',
        'description' => 'Vert émeraude RSE — entreprises à impact positif et développement durable.',
        'plan_min'    => 'pro',
        'primary'     => '#065F46',
        'secondary'   => '#022C22',
        'accent'      => '#34D399',
    ],
    'corporate-red' => [
        'name'        => 'Corporate Red',
        'family'      => 'Corporate',
        'description' => 'Héro rouge passion — entreprises dynamiques et secteur commercial.',
        'plan_min'    => 'pro',
        'primary'     => '#991B1B',
        'secondary'   => '#7F1D1D',
        'accent'      => '#F87171',
    ],
    'corporate-teal' => [
        'name'        => 'Corporate Teal',
        'family'      => 'Corporate',
        'description' => 'Sarcelle minimaliste — startups modernes et services numériques.',
        'plan_min'    => 'starter',
        'primary'     => '#0D9488',
        'secondary'   => '#0F766E',
        'accent'      => '#F59E0B',
    ],

    // ══════════════════════════════════════════════════════════════════════
    // ── FINANCE (8) ───────────────────────────────────────────────────────
    // ══════════════════════════════════════════════════════════════════════
    'finance-classic' => [
        'name'        => 'Finance Classic',
        'family'      => 'Finance',
        'description' => 'Bleu banque et cyan aqua — cabinets comptables, expert-comptables.',
        'plan_min'    => 'pro',
        'primary'     => '#1E3A5F',
        'secondary'   => '#0D2137',
        'accent'      => '#2DD4BF',
    ],
    'finance-dark' => [
        'name'        => 'Finance Dark',
        'family'      => 'Finance',
        'description' => 'Nuit profonde et cyan électrique — fintech et trading.',
        'plan_min'    => 'pro',
        'primary'     => '#0C0C1E',
        'secondary'   => '#060611',
        'accent'      => '#00E5FF',
    ],
    'finance-gold' => [
        'name'        => 'Finance Gold',
        'family'      => 'Finance',
        'description' => 'Luxe or sur noir — banques privées et gestion de patrimoine.',
        'plan_min'    => 'enterprise',
        'primary'     => '#1A1008',
        'secondary'   => '#0A0804',
        'accent'      => '#C9922A',
    ],
    'finance-minimal' => [
        'name'        => 'Finance Minimal',
        'family'      => 'Finance',
        'description' => 'Minimalisme graphite et vert — bilans et rapports financiers sobres.',
        'plan_min'    => 'starter',
        'primary'     => '#1F2937',
        'secondary'   => '#111827',
        'accent'      => '#10B981',
    ],
    'finance-trust' => [
        'name'        => 'Finance Trust',
        'family'      => 'Finance',
        'description' => 'Marine institutionnel et or — confiance et sécurité bancaire.',
        'plan_min'    => 'pro',
        'primary'     => '#003366',
        'secondary'   => '#001A33',
        'accent'      => '#F0C040',
    ],
    'finance-modern' => [
        'name'        => 'Finance Modern',
        'family'      => 'Finance',
        'description' => 'Zinc sombre et bleu digital — néobanques et services financiers modernes.',
        'plan_min'    => 'pro',
        'primary'     => '#18181B',
        'secondary'   => '#0A0A0B',
        'accent'      => '#60A5FA',
    ],
    'finance-clean' => [
        'name'        => 'Finance Clean',
        'family'      => 'Finance',
        'description' => 'Charcoal minimal et indigo — rapports épurés pour investisseurs.',
        'plan_min'    => 'starter',
        'primary'     => '#111827',
        'secondary'   => '#030712',
        'accent'      => '#6366F1',
    ],
    'finance-prestige' => [
        'name'        => 'Finance Prestige',
        'family'      => 'Finance',
        'description' => 'Noir absolu et ambre luxe — wealth management et private equity.',
        'plan_min'    => 'enterprise',
        'primary'     => '#0A0A0A',
        'secondary'   => '#050505',
        'accent'      => '#D97706',
    ],

    // ══════════════════════════════════════════════════════════════════════
    // ── TECH / SAAS (8) ───────────────────────────────────────────────────
    // ══════════════════════════════════════════════════════════════════════
    'tech-dark' => [
        'name'        => 'Tech Dark',
        'family'      => 'Tech & SaaS',
        'description' => 'Slate sombre et vert terminal — développeurs et agences tech.',
        'plan_min'    => 'pro',
        'primary'     => '#0F172A',
        'secondary'   => '#020617',
        'accent'      => '#3FB950',
    ],
    'tech-neon' => [
        'name'        => 'Tech Neon',
        'family'      => 'Tech & SaaS',
        'description' => 'Nuit cyber et cyan électrique — gaming, cybersécurité, IA.',
        'plan_min'    => 'pro',
        'primary'     => '#020617',
        'secondary'   => '#000308',
        'accent'      => '#00E5FF',
    ],
    'tech-purple' => [
        'name'        => 'Tech Purple',
        'family'      => 'Tech & SaaS',
        'description' => 'Violet profond et lavande — startups créatives et apps mobiles.',
        'plan_min'    => 'pro',
        'primary'     => '#4C1D95',
        'secondary'   => '#2E1065',
        'accent'      => '#A78BFA',
    ],
    'tech-minimal' => [
        'name'        => 'Tech Minimal',
        'family'      => 'Tech & SaaS',
        'description' => 'Slate et bleu ciel — SaaS B2B, documentation technique sobre.',
        'plan_min'    => 'starter',
        'primary'     => '#1E293B',
        'secondary'   => '#0F172A',
        'accent'      => '#38BDF8',
    ],
    'tech-saas' => [
        'name'        => 'Tech SaaS',
        'family'      => 'Tech & SaaS',
        'description' => 'Charcoal et rose fuchsia — produits SaaS modernes et marketplaces.',
        'plan_min'    => 'pro',
        'primary'     => '#111827',
        'secondary'   => '#030712',
        'accent'      => '#F472B6',
    ],
    'tech-github' => [
        'name'        => 'Tech GitHub',
        'family'      => 'Tech & SaaS',
        'description' => 'Nuit GitHub et bleu octocat — open source, développeurs, DevOps.',
        'plan_min'    => 'pro',
        'primary'     => '#0D1117',
        'secondary'   => '#010409',
        'accent'      => '#58A6FF',
    ],
    'tech-startup' => [
        'name'        => 'Tech Startup',
        'family'      => 'Tech & SaaS',
        'description' => 'Héro bleu acier et menthe — startups en phase de croissance.',
        'plan_min'    => 'pro',
        'primary'     => '#1E3A5F',
        'secondary'   => '#0D2137',
        'accent'      => '#34D399',
    ],
    'tech-clean' => [
        'name'        => 'Tech Clean',
        'family'      => 'Tech & SaaS',
        'description' => 'Minimalisme sombre et indigo — applications enterprise et B2B.',
        'plan_min'    => 'starter',
        'primary'     => '#0F172A',
        'secondary'   => '#020617',
        'accent'      => '#818CF8',
    ],

    // ══════════════════════════════════════════════════════════════════════
    // ── AFRIQUE (10) ──────────────────────────────────────────────────────
    // ══════════════════════════════════════════════════════════════════════
    'africa-kente' => [
        'name'        => 'Africa Kente',
        'family'      => 'Afrique',
        'description' => 'Or kente et ambre — inspiré des tissus royaux d\'Afrique de l\'Ouest.',
        'plan_min'    => 'starter',
        'primary'     => '#B45309',
        'secondary'   => '#92400E',
        'accent'      => '#D97706',
    ],
    'africa-baobab' => [
        'name'        => 'Africa Baobab',
        'family'      => 'Afrique',
        'description' => 'Vert savane et or soleil — nature africaine et agriculture.',
        'plan_min'    => 'starter',
        'primary'     => '#065F46',
        'secondary'   => '#022C22',
        'accent'      => '#F59E0B',
    ],
    'africa-sahel' => [
        'name'        => 'Africa Sahel',
        'family'      => 'Afrique',
        'description' => 'Terre d\'ocre et ambre — commerce sahelien et artisanat.',
        'plan_min'    => 'starter',
        'primary'     => '#92400E',
        'secondary'   => '#78350F',
        'accent'      => '#D97706',
    ],
    'africa-dakar' => [
        'name'        => 'Africa Dakar',
        'family'      => 'Afrique',
        'description' => 'Nuit dakaroise et or — entreprises modernes du Sénégal.',
        'plan_min'    => 'pro',
        'primary'     => '#1A1A2E',
        'secondary'   => '#0F0F1A',
        'accent'      => '#F59E0B',
    ],
    'africa-abidjan' => [
        'name'        => 'Africa Abidjan',
        'family'      => 'Afrique',
        'description' => 'Bleu lagune et or — dynamisme économique de Côte d\'Ivoire.',
        'plan_min'    => 'starter',
        'primary'     => '#1B4FA8',
        'secondary'   => '#0D2A5E',
        'accent'      => '#F59E0B',
    ],
    'africa-lagos' => [
        'name'        => 'Africa Lagos',
        'family'      => 'Afrique',
        'description' => 'Vert émeraude et vert clair — vitalité économique du Nigeria.',
        'plan_min'    => 'starter',
        'primary'     => '#166534',
        'secondary'   => '#14532D',
        'accent'      => '#4ADE80',
    ],
    'africa-kinshasa' => [
        'name'        => 'Africa Kinshasa',
        'family'      => 'Afrique',
        'description' => 'Héro terre brûlée et or — richesse et potentiel de l\'Afrique centrale.',
        'plan_min'    => 'starter',
        'primary'     => '#7C2D12',
        'secondary'   => '#5A1F0D',
        'accent'      => '#FCD34D',
    ],
    'africa-casablanca' => [
        'name'        => 'Africa Casablanca',
        'family'      => 'Afrique',
        'description' => 'Marine nuit et émeraude — élégance maghrébine et commerce med.',
        'plan_min'    => 'pro',
        'primary'     => '#1E3A5F',
        'secondary'   => '#0D2137',
        'accent'      => '#34D399',
    ],
    'africa-accra' => [
        'name'        => 'Africa Accra',
        'family'      => 'Afrique',
        'description' => 'Ardoise et turquoise — hub tech d\'Afrique, Silicon Savannah.',
        'plan_min'    => 'starter',
        'primary'     => '#1F2937',
        'secondary'   => '#111827',
        'accent'      => '#10B981',
    ],
    'africa-premium' => [
        'name'        => 'Africa Premium',
        'family'      => 'Afrique',
        'description' => 'Luxe africain — noir et or pour les entreprises panafricaines premium.',
        'plan_min'    => 'enterprise',
        'primary'     => '#1A1008',
        'secondary'   => '#0A0804',
        'accent'      => '#D97706',
    ],

    // ══════════════════════════════════════════════════════════════════════
    // ── MÉDICAL / SANTÉ (6) ───────────────────────────────────────────────
    // ══════════════════════════════════════════════════════════════════════
    'medical-classic' => [
        'name'        => 'Medical Classic',
        'family'      => 'Médical',
        'description' => 'Bleu confiance et cyan — cliniques, cabinets médicaux, pharmacies.',
        'plan_min'    => 'pro',
        'primary'     => '#0369A1',
        'secondary'   => '#075985',
        'accent'      => '#38BDF8',
    ],
    'medical-minimal' => [
        'name'        => 'Medical Minimal',
        'family'      => 'Médical',
        'description' => 'Bleu épuré — ordonnances, prescriptions, factures médicales sobres.',
        'plan_min'    => 'starter',
        'primary'     => '#1E40AF',
        'secondary'   => '#1E3A8A',
        'accent'      => '#3B82F6',
    ],
    'medical-clean' => [
        'name'        => 'Medical Clean',
        'family'      => 'Médical',
        'description' => 'Vert santé minimaliste — médecine naturelle, bien-être, nutrition.',
        'plan_min'    => 'starter',
        'primary'     => '#065F46',
        'secondary'   => '#022C22',
        'accent'      => '#34D399',
    ],
    'medical-dark' => [
        'name'        => 'Medical Dark',
        'family'      => 'Médical',
        'description' => 'Header sombre et bleu ciel — hôpitaux modernes, imagerie médicale.',
        'plan_min'    => 'pro',
        'primary'     => '#0F172A',
        'secondary'   => '#020617',
        'accent'      => '#38BDF8',
    ],
    'medical-hero' => [
        'name'        => 'Medical Hero',
        'family'      => 'Médical',
        'description' => 'Bandeau bleu acier — établissements de soins et cliniques spécialisées.',
        'plan_min'    => 'pro',
        'primary'     => '#1E3A5F',
        'secondary'   => '#0D2137',
        'accent'      => '#60A5FA',
    ],
    'medical-premium' => [
        'name'        => 'Medical Premium',
        'family'      => 'Médical',
        'description' => 'Sarcelle élite — centres médicaux premium et médecine esthétique.',
        'plan_min'    => 'pro',
        'primary'     => '#134E4A',
        'secondary'   => '#0F3D3A',
        'accent'      => '#2DD4BF',
    ],

    // ══════════════════════════════════════════════════════════════════════
    // ── BTP / CONSTRUCTION (5) ────────────────────────────────────────────
    // ══════════════════════════════════════════════════════════════════════
    'btp-classic' => [
        'name'        => 'BTP Classic',
        'family'      => 'BTP',
        'description' => 'Terre ocre et ambre — entreprises de construction et maçonnerie.',
        'plan_min'    => 'starter',
        'primary'     => '#92400E',
        'secondary'   => '#78350F',
        'accent'      => '#F59E0B',
    ],
    'btp-industrial' => [
        'name'        => 'BTP Industrial',
        'family'      => 'BTP',
        'description' => 'Header sombre et orange industriel — génie civil, métallurgie.',
        'plan_min'    => 'pro',
        'primary'     => '#1C1917',
        'secondary'   => '#0C0A09',
        'accent'      => '#F97316',
    ],
    'btp-orange' => [
        'name'        => 'BTP Orange',
        'family'      => 'BTP',
        'description' => 'Héro brique et orange vif — chantiers, sécurité, travaux publics.',
        'plan_min'    => 'starter',
        'primary'     => '#7C2D12',
        'secondary'   => '#5A1F0D',
        'accent'      => '#F97316',
    ],
    'btp-safety' => [
        'name'        => 'BTP Safety',
        'family'      => 'BTP',
        'description' => 'Gris anthracite et jaune sécurité — devis chantier, EPI, maintenance.',
        'plan_min'    => 'starter',
        'primary'     => '#1F2937',
        'secondary'   => '#111827',
        'accent'      => '#FBBF24',
    ],
    'btp-premium' => [
        'name'        => 'BTP Premium',
        'family'      => 'BTP',
        'description' => 'Header sombre et or — promoteurs immobiliers, architectes, BET.',
        'plan_min'    => 'pro',
        'primary'     => '#111827',
        'secondary'   => '#030712',
        'accent'      => '#D97706',
    ],

    // ══════════════════════════════════════════════════════════════════════
    // ── BEAUTÉ / BIEN-ÊTRE (5) ────────────────────────────────────────────
    // ══════════════════════════════════════════════════════════════════════
    'beauty-rose' => [
        'name'        => 'Beauty Rose',
        'family'      => 'Beauté',
        'description' => 'Héro rose profond — instituts de beauté, spas, coiffeurs.',
        'plan_min'    => 'pro',
        'primary'     => '#831843',
        'secondary'   => '#500724',
        'accent'      => '#F9A8D4',
    ],
    'beauty-luxury' => [
        'name'        => 'Beauty Luxury',
        'family'      => 'Beauté',
        'description' => 'Luxe sombre et or — parfumeries, cosmétiques haut de gamme.',
        'plan_min'    => 'enterprise',
        'primary'     => '#1C1917',
        'secondary'   => '#0C0A09',
        'accent'      => '#D97706',
    ],
    'beauty-minimal' => [
        'name'        => 'Beauty Minimal',
        'family'      => 'Beauté',
        'description' => 'Violet minimal et lilas — soins naturels, cosmétique bio.',
        'plan_min'    => 'starter',
        'primary'     => '#6B21A8',
        'secondary'   => '#581C87',
        'accent'      => '#C084FC',
    ],
    'beauty-elegant' => [
        'name'        => 'Beauty Elegant',
        'family'      => 'Beauté',
        'description' => 'Prune élégant et fuchsia — salons de beauté et ongleries premium.',
        'plan_min'    => 'pro',
        'primary'     => '#4A1942',
        'secondary'   => '#3B1434',
        'accent'      => '#E879F9',
    ],
    'beauty-glam' => [
        'name'        => 'Beauty Glam',
        'family'      => 'Beauté',
        'description' => 'Héro glamour fuchsia — make-up artiste, stylistes, fashion.',
        'plan_min'    => 'pro',
        'primary'     => '#7C1D4A',
        'secondary'   => '#5A1435',
        'accent'      => '#F9A8D4',
    ],

    // ══════════════════════════════════════════════════════════════════════
    // ── IMMOBILIER (5) ────────────────────────────────────────────────────
    // ══════════════════════════════════════════════════════════════════════
    'immo-classic' => [
        'name'        => 'Immo Classic',
        'family'      => 'Immobilier',
        'description' => 'Bleu acier et or — agences immobilières et promoteurs.',
        'plan_min'    => 'starter',
        'primary'     => '#1E3A5F',
        'secondary'   => '#0D2137',
        'accent'      => '#F59E0B',
    ],
    'immo-dark' => [
        'name'        => 'Immo Dark',
        'family'      => 'Immobilier',
        'description' => 'Header sombre et bleu — locations saisonnières, agences urbaines.',
        'plan_min'    => 'pro',
        'primary'     => '#0F172A',
        'secondary'   => '#020617',
        'accent'      => '#60A5FA',
    ],
    'immo-luxury' => [
        'name'        => 'Immo Luxury',
        'family'      => 'Immobilier',
        'description' => 'Noir et or — immobilier de prestige, biens d\'exception.',
        'plan_min'    => 'enterprise',
        'primary'     => '#0A0A0A',
        'secondary'   => '#050505',
        'accent'      => '#C9922A',
    ],
    'immo-hero' => [
        'name'        => 'Immo Hero',
        'family'      => 'Immobilier',
        'description' => 'Bandeau bleu marine et or — compromis, actes et mandats.',
        'plan_min'    => 'pro',
        'primary'     => '#1B4FA8',
        'secondary'   => '#0D2A5E',
        'accent'      => '#F0C040',
    ],
    'immo-minimal' => [
        'name'        => 'Immo Minimal',
        'family'      => 'Immobilier',
        'description' => 'Ardoise et indigo — gestionnaires de biens et administrateurs.',
        'plan_min'    => 'starter',
        'primary'     => '#374151',
        'secondary'   => '#1F2937',
        'accent'      => '#6366F1',
    ],

    // ══════════════════════════════════════════════════════════════════════
    // ── CRÉATIF / AGENCE (8) ──────────────────────────────────────────────
    // ══════════════════════════════════════════════════════════════════════
    'creative-dark' => [
        'name'        => 'Creative Dark',
        'family'      => 'Créatif',
        'description' => 'Indigo profond et lavande — agences digitales et studios design.',
        'plan_min'    => 'pro',
        'primary'     => '#1E1B4B',
        'secondary'   => '#0F0D2E',
        'accent'      => '#818CF8',
    ],
    'creative-neon' => [
        'name'        => 'Creative Neon',
        'family'      => 'Créatif',
        'description' => 'Nuit slate et rose néon — motion design, VFX, production créative.',
        'plan_min'    => 'pro',
        'primary'     => '#0F172A',
        'secondary'   => '#020617',
        'accent'      => '#F472B6',
    ],
    'creative-hero' => [
        'name'        => 'Creative Hero',
        'family'      => 'Créatif',
        'description' => 'Héro violet et améthyste — creative agencies et branding studios.',
        'plan_min'    => 'pro',
        'primary'     => '#4C1D95',
        'secondary'   => '#2E1065',
        'accent'      => '#A78BFA',
    ],
    'creative-bold' => [
        'name'        => 'Creative Bold',
        'family'      => 'Créatif',
        'description' => 'Héro framboise et corail — illustrations, photography, content.',
        'plan_min'    => 'pro',
        'primary'     => '#831843',
        'secondary'   => '#500724',
        'accent'      => '#FB7185',
    ],
    'creative-minimal' => [
        'name'        => 'Creative Minimal',
        'family'      => 'Créatif',
        'description' => 'Minimal sombre et indigo — portfolios, freelances créatifs.',
        'plan_min'    => 'starter',
        'primary'     => '#0F172A',
        'secondary'   => '#020617',
        'accent'      => '#818CF8',
    ],
    'creative-sidebar' => [
        'name'        => 'Creative Sidebar',
        'family'      => 'Créatif',
        'description' => 'Bande latérale indigo — agences modernes avec signature visuelle forte.',
        'plan_min'    => 'pro',
        'primary'     => '#1E1B4B',
        'secondary'   => '#0F0D2E',
        'accent'      => '#818CF8',
    ],
    'creative-orange' => [
        'name'        => 'Creative Orange',
        'family'      => 'Créatif',
        'description' => 'Header brique et orange — imprimeries, signalétique, communication.',
        'plan_min'    => 'pro',
        'primary'     => '#7C2D12',
        'secondary'   => '#5A1F0D',
        'accent'      => '#F97316',
    ],
    'creative-studio' => [
        'name'        => 'Creative Studio',
        'family'      => 'Créatif',
        'description' => 'Héro charbon et ambre — studios photo et production audiovisuelle.',
        'plan_min'    => 'pro',
        'primary'     => '#1C1917',
        'secondary'   => '#0C0A09',
        'accent'      => '#F59E0B',
    ],

    // ══════════════════════════════════════════════════════════════════════
    // ── HÔTELLERIE / RESTAURATION (7) ─────────────────────────────────────
    // ══════════════════════════════════════════════════════════════════════
    'hotel-luxury' => [
        'name'        => 'Hotel Luxury',
        'family'      => 'Hôtellerie',
        'description' => 'Luxe noir et or — hôtels 5 étoiles, palaces, resorts premium.',
        'plan_min'    => 'enterprise',
        'primary'     => '#0A0A0A',
        'secondary'   => '#050505',
        'accent'      => '#C9922A',
    ],
    'hotel-classic' => [
        'name'        => 'Hotel Classic',
        'family'      => 'Hôtellerie',
        'description' => 'Marine et or classique — hôtels boutique et établissements élégants.',
        'plan_min'    => 'pro',
        'primary'     => '#1B4FA8',
        'secondary'   => '#0D2A5E',
        'accent'      => '#F0C040',
    ],
    'hotel-dark' => [
        'name'        => 'Hotel Dark',
        'family'      => 'Hôtellerie',
        'description' => 'Sombre et or chaud — hôtels design et expériences uniques.',
        'plan_min'    => 'pro',
        'primary'     => '#0F172A',
        'secondary'   => '#020617',
        'accent'      => '#F59E0B',
    ],
    'hotel-hero' => [
        'name'        => 'Hotel Hero',
        'family'      => 'Hôtellerie',
        'description' => 'Héro brique et orange — lodges, gîtes, hébergements atypiques.',
        'plan_min'    => 'pro',
        'primary'     => '#7C2D12',
        'secondary'   => '#5A1F0D',
        'accent'      => '#F97316',
    ],
    'resto-classic' => [
        'name'        => 'Resto Classic',
        'family'      => 'Restauration',
        'description' => 'Rouge passion et or — restaurants gastronomiques et brasseries.',
        'plan_min'    => 'starter',
        'primary'     => '#991B1B',
        'secondary'   => '#7F1D1D',
        'accent'      => '#FBBF24',
    ],
    'resto-dark' => [
        'name'        => 'Resto Dark',
        'family'      => 'Restauration',
        'description' => 'Header charbon et orange — food trucks, street food, fast casual.',
        'plan_min'    => 'pro',
        'primary'     => '#1C1917',
        'secondary'   => '#0C0A09',
        'accent'      => '#F97316',
    ],
    'resto-luxury' => [
        'name'        => 'Resto Luxury',
        'family'      => 'Restauration',
        'description' => 'Luxe sombre et or — tables étoilées et expériences gastronomiques.',
        'plan_min'    => 'enterprise',
        'primary'     => '#1A1008',
        'secondary'   => '#0A0804',
        'accent'      => '#D97706',
    ],

    // ══════════════════════════════════════════════════════════════════════
    // ── JURIDIQUE / LÉGAL (6) ─────────────────────────────────────────────
    // ══════════════════════════════════════════════════════════════════════
    'legal-minimal' => [
        'name'        => 'Légal Minimal',
        'family'      => 'Juridique',
        'description' => 'Ardoise épuré et indigo — avocats et juristes sobres.',
        'plan_min'    => 'pro',
        'primary'     => '#374151',
        'secondary'   => '#1F2937',
        'accent'      => '#6366F1',
    ],
    'legal-classic' => [
        'name'        => 'Légal Classic',
        'family'      => 'Juridique',
        'description' => 'Marine institutionnel et or — cabinets d\'avocats établis.',
        'plan_min'    => 'pro',
        'primary'     => '#1E3A5F',
        'secondary'   => '#0D2137',
        'accent'      => '#F0C040',
    ],
    'legal-dark' => [
        'name'        => 'Légal Dark',
        'family'      => 'Juridique',
        'description' => 'Header nuit et bleu — droit des affaires, M&A, corporate.',
        'plan_min'    => 'pro',
        'primary'     => '#0F172A',
        'secondary'   => '#020617',
        'accent'      => '#60A5FA',
    ],
    'legal-prestige' => [
        'name'        => 'Légal Prestige',
        'family'      => 'Juridique',
        'description' => 'Graphite minimal et émeraude — cabinets d\'affaires internationaux.',
        'plan_min'    => 'pro',
        'primary'     => '#1F2937',
        'secondary'   => '#111827',
        'accent'      => '#10B981',
    ],
    'legal-notaire' => [
        'name'        => 'Légal Notaire',
        'family'      => 'Juridique',
        'description' => 'Marine royal et or — notaires, huissiers, officiers ministériels.',
        'plan_min'    => 'pro',
        'primary'     => '#003366',
        'secondary'   => '#001A33',
        'accent'      => '#C9922A',
    ],
    'legal-avocats' => [
        'name'        => 'Légal Avocats',
        'family'      => 'Juridique',
        'description' => 'Minimal charcoal et indigo — jeunes barreaux et legal tech.',
        'plan_min'    => 'starter',
        'primary'     => '#111827',
        'secondary'   => '#030712',
        'accent'      => '#818CF8',
    ],

    // ══════════════════════════════════════════════════════════════════════
    // ── TRANSPORT / LOGISTIQUE (5) ────────────────────────────────────────
    // ══════════════════════════════════════════════════════════════════════
    'transport-dark' => [
        'name'        => 'Transport Dark',
        'family'      => 'Transport',
        'description' => 'Header charbon et orange — transporteurs routiers et logisticiens.',
        'plan_min'    => 'pro',
        'primary'     => '#1C1917',
        'secondary'   => '#0C0A09',
        'accent'      => '#F97316',
    ],
    'transport-classic' => [
        'name'        => 'Transport Classic',
        'family'      => 'Transport',
        'description' => 'Bleu acier et or — compagnies maritimes et aériennes.',
        'plan_min'    => 'starter',
        'primary'     => '#1E3A5F',
        'secondary'   => '#0D2137',
        'accent'      => '#F59E0B',
    ],
    'transport-hero' => [
        'name'        => 'Transport Hero',
        'family'      => 'Transport',
        'description' => 'Héro brique et orange — entreprises de messagerie et coursiers.',
        'plan_min'    => 'pro',
        'primary'     => '#7C2D12',
        'secondary'   => '#5A1F0D',
        'accent'      => '#F97316',
    ],
    'transport-logistic' => [
        'name'        => 'Transport Logistic',
        'family'      => 'Transport',
        'description' => 'Sombre et bleu — entrepôts, supply chain, 3PL.',
        'plan_min'    => 'pro',
        'primary'     => '#0F172A',
        'secondary'   => '#020617',
        'accent'      => '#3B82F6',
    ],
    'transport-fleet' => [
        'name'        => 'Transport Fleet',
        'family'      => 'Transport',
        'description' => 'Anthracite et jaune — gestionnaires de flotte et mainteneurs.',
        'plan_min'    => 'starter',
        'primary'     => '#1F2937',
        'secondary'   => '#111827',
        'accent'      => '#FBBF24',
    ],

    // ══════════════════════════════════════════════════════════════════════
    // ── AGRICULTURE / AGROALIMENTAIRE (5) ─────────────────────────────────
    // ══════════════════════════════════════════════════════════════════════
    'agri-classic' => [
        'name'        => 'Agri Classic',
        'family'      => 'Agriculture',
        'description' => 'Vert feuille et citron vert — coopératives et exploitations agricoles.',
        'plan_min'    => 'starter',
        'primary'     => '#065F46',
        'secondary'   => '#022C22',
        'accent'      => '#84CC16',
    ],
    'agri-hero' => [
        'name'        => 'Agri Hero',
        'family'      => 'Agriculture',
        'description' => 'Héro vert profond — agroindustrie et transformation alimentaire.',
        'plan_min'    => 'starter',
        'primary'     => '#3F6212',
        'secondary'   => '#2D4A0D',
        'accent'      => '#84CC16',
    ],
    'agri-minimal' => [
        'name'        => 'Agri Minimal',
        'family'      => 'Agriculture',
        'description' => 'Minimal vert forêt — semenciers, pépiniéristes, maraîchers.',
        'plan_min'    => 'starter',
        'primary'     => '#1A2E05',
        'secondary'   => '#0D1702',
        'accent'      => '#84CC16',
    ],
    'agri-terroir' => [
        'name'        => 'Agri Terroir',
        'family'      => 'Agriculture',
        'description' => 'Terre de Sienne et ambre — viticulture, fromageries, terroir.',
        'plan_min'    => 'starter',
        'primary'     => '#92400E',
        'secondary'   => '#78350F',
        'accent'      => '#D97706',
    ],
    'agri-premium' => [
        'name'        => 'Agri Premium',
        'family'      => 'Agriculture',
        'description' => 'Vert profond et or — labels bio premium et appellations d\'origine.',
        'plan_min'    => 'pro',
        'primary'     => '#065F46',
        'secondary'   => '#022C22',
        'accent'      => '#F59E0B',
    ],

    // ══════════════════════════════════════════════════════════════════════
    // ── ÉDUCATION / FORMATION (6) ─────────────────────────────────────────
    // ══════════════════════════════════════════════════════════════════════
    'edu-classic' => [
        'name'        => 'Éducation Classic',
        'family'      => 'Éducation',
        'description' => 'Bleu académique et or — universités, grandes écoles, instituts.',
        'plan_min'    => 'starter',
        'primary'     => '#1E3A5F',
        'secondary'   => '#0D2137',
        'accent'      => '#F0C040',
    ],
    'edu-hero' => [
        'name'        => 'Éducation Hero',
        'family'      => 'Éducation',
        'description' => 'Héro bleu roi — centres de formation professionnelle et CFA.',
        'plan_min'    => 'starter',
        'primary'     => '#1B4FA8',
        'secondary'   => '#0D2A5E',
        'accent'      => '#F59E0B',
    ],
    'edu-minimal' => [
        'name'        => 'Éducation Minimal',
        'family'      => 'Éducation',
        'description' => 'Ardoise et indigo — cours particuliers, tuteurs, e-learning.',
        'plan_min'    => 'starter',
        'primary'     => '#374151',
        'secondary'   => '#1F2937',
        'accent'      => '#6366F1',
    ],
    'edu-dark' => [
        'name'        => 'Éducation Dark',
        'family'      => 'Éducation',
        'description' => 'Nuit indigo et lavande — bootcamps tech et formations numériques.',
        'plan_min'    => 'pro',
        'primary'     => '#1E1B4B',
        'secondary'   => '#0F0D2E',
        'accent'      => '#818CF8',
    ],
    'edu-bright' => [
        'name'        => 'Éducation Bright',
        'family'      => 'Éducation',
        'description' => 'Héro vert vif — jeunesse, associations éducatives, ONG.',
        'plan_min'    => 'starter',
        'primary'     => '#065F46',
        'secondary'   => '#022C22',
        'accent'      => '#34D399',
    ],
    'edu-prestige' => [
        'name'        => 'Éducation Prestige',
        'family'      => 'Éducation',
        'description' => 'Prune et orchidée — académies artistiques et écoles de luxe.',
        'plan_min'    => 'pro',
        'primary'     => '#7C1D4A',
        'secondary'   => '#5A1435',
        'accent'      => '#F9A8D4',
    ],

    // ══════════════════════════════════════════════════════════════════════
    // ── LUXE (5) ──────────────────────────────────────────────────────────
    // ══════════════════════════════════════════════════════════════════════
    'luxe-noir' => [
        'name'        => 'Luxe Noir',
        'family'      => 'Luxe',
        'description' => 'Noir absolu et or — maisons de couture, haute joaillerie.',
        'plan_min'    => 'enterprise',
        'primary'     => '#0A0A0A',
        'secondary'   => '#050505',
        'accent'      => '#C9922A',
    ],
    'luxe-gold' => [
        'name'        => 'Luxe Gold',
        'family'      => 'Luxe',
        'description' => 'Nuit chaude et or chaud — champagne, haute gastronomie, prestige.',
        'plan_min'    => 'enterprise',
        'primary'     => '#1A1008',
        'secondary'   => '#0A0804',
        'accent'      => '#D97706',
    ],
    'luxe-platinum' => [
        'name'        => 'Luxe Platinum',
        'family'      => 'Luxe',
        'description' => 'Charbon et platine — horlogerie, automobiles premium.',
        'plan_min'    => 'enterprise',
        'primary'     => '#1C1917',
        'secondary'   => '#0C0A09',
        'accent'      => '#E2E8F0',
    ],
    'luxe-dark' => [
        'name'        => 'Luxe Dark',
        'family'      => 'Luxe',
        'description' => 'Header nuit et or discret — conciergerie privée et services exclusifs.',
        'plan_min'    => 'enterprise',
        'primary'     => '#0F172A',
        'secondary'   => '#020617',
        'accent'      => '#C9922A',
    ],
    'luxe-minimal' => [
        'name'        => 'Luxe Minimal',
        'family'      => 'Luxe',
        'description' => 'Minimal charcoal et or — maisons d\'édition de luxe, art galleries.',
        'plan_min'    => 'pro',
        'primary'     => '#111827',
        'secondary'   => '#030712',
        'accent'      => '#C9922A',
    ],

    // ══════════════════════════════════════════════════════════════════════
    // ── SPORT / FITNESS (5) ───────────────────────────────────────────────
    // ══════════════════════════════════════════════════════════════════════
    'sport-hero' => [
        'name'        => 'Sport Hero',
        'family'      => 'Sport',
        'description' => 'Héro bleu acier et or — clubs sportifs professionnels.',
        'plan_min'    => 'pro',
        'primary'     => '#1E3A5F',
        'secondary'   => '#0D2137',
        'accent'      => '#F59E0B',
    ],
    'sport-dark' => [
        'name'        => 'Sport Dark',
        'family'      => 'Sport',
        'description' => 'Header nuit et vert — salles de sport, coachs fitness.',
        'plan_min'    => 'pro',
        'primary'     => '#0F172A',
        'secondary'   => '#020617',
        'accent'      => '#3FB950',
    ],
    'sport-energy' => [
        'name'        => 'Sport Energy',
        'family'      => 'Sport',
        'description' => 'Héro rouge énergie — sports extrêmes, athlétisme, compétition.',
        'plan_min'    => 'pro',
        'primary'     => '#7C2D12',
        'secondary'   => '#5A1F0D',
        'accent'      => '#F97316',
    ],
    'sport-neon' => [
        'name'        => 'Sport Neon',
        'family'      => 'Sport',
        'description' => 'Nuit cyber et cyan — e-sport, gaming, sports digitaux.',
        'plan_min'    => 'pro',
        'primary'     => '#020617',
        'secondary'   => '#000308',
        'accent'      => '#00E5FF',
    ],
    'sport-classic' => [
        'name'        => 'Sport Classic',
        'family'      => 'Sport',
        'description' => 'Bleu marine et or — fédérations sportives et associations.',
        'plan_min'    => 'starter',
        'primary'     => '#1B4FA8',
        'secondary'   => '#0D2A5E',
        'accent'      => '#F0C040',
    ],

    // ══════════════════════════════════════════════════════════════════════
    // ── ONG / ASSOCIATION (4) ─────────────────────────────────────────────
    // ══════════════════════════════════════════════════════════════════════
    'ong-classic' => [
        'name'        => 'ONG Classic',
        'family'      => 'ONG',
        'description' => 'Vert espoir et émeraude — associations humanitaires et environnement.',
        'plan_min'    => 'starter',
        'primary'     => '#065F46',
        'secondary'   => '#022C22',
        'accent'      => '#34D399',
    ],
    'ong-hero' => [
        'name'        => 'ONG Hero',
        'family'      => 'ONG',
        'description' => 'Héro bleu solidarité — ONG internationales et fondations.',
        'plan_min'    => 'starter',
        'primary'     => '#1E3A5F',
        'secondary'   => '#0D2137',
        'accent'      => '#60A5FA',
    ],
    'ong-minimal' => [
        'name'        => 'ONG Minimal',
        'family'      => 'ONG',
        'description' => 'Minimal ardoise et vert — associations locales et bénévolat.',
        'plan_min'    => 'starter',
        'primary'     => '#374151',
        'secondary'   => '#1F2937',
        'accent'      => '#10B981',
    ],
    'ong-impact' => [
        'name'        => 'ONG Impact',
        'family'      => 'ONG',
        'description' => 'Héro rouge engagement — campagnes de sensibilisation et urgence.',
        'plan_min'    => 'pro',
        'primary'     => '#7C2D12',
        'secondary'   => '#5A1F0D',
        'accent'      => '#F97316',
    ],

    // ══════════════════════════════════════════════════════════════════════
    // ── DIGITAL / MARKETING (4) ───────────────────────────────────────────
    // ══════════════════════════════════════════════════════════════════════
    'digital-dark' => [
        'name'        => 'Digital Dark',
        'family'      => 'Digital',
        'description' => 'Slate sombre et indigo — agences SEO/SEA et growth hacking.',
        'plan_min'    => 'pro',
        'primary'     => '#0F172A',
        'secondary'   => '#020617',
        'accent'      => '#818CF8',
    ],
    'digital-hero' => [
        'name'        => 'Digital Hero',
        'family'      => 'Digital',
        'description' => 'Héro violet et améthyste — social media, influenceurs, creators.',
        'plan_min'    => 'pro',
        'primary'     => '#4C1D95',
        'secondary'   => '#2E1065',
        'accent'      => '#A78BFA',
    ],
    'digital-neon' => [
        'name'        => 'Digital Neon',
        'family'      => 'Digital',
        'description' => 'Cyber nuit et fuchsia — marketing digital agressif et disruption.',
        'plan_min'    => 'pro',
        'primary'     => '#020617',
        'secondary'   => '#000308',
        'accent'      => '#F472B6',
    ],
    'digital-sidebar' => [
        'name'        => 'Digital Sidebar',
        'family'      => 'Digital',
        'description' => 'Bande latérale slate — agences avec identité visuelle distinctive.',
        'plan_min'    => 'pro',
        'primary'     => '#0F172A',
        'secondary'   => '#020617',
        'accent'      => '#818CF8',
    ],

    // ══════════════════════════════════════════════════════════════════════
    // ── AUTO / MOTO (4) ───────────────────────────────────────────────────
    // ══════════════════════════════════════════════════════════════════════
    'auto-classic' => [
        'name'        => 'Auto Classic',
        'family'      => 'Automobile',
        'description' => 'Anthracite et or — concessions et garages automobiles.',
        'plan_min'    => 'starter',
        'primary'     => '#1F2937',
        'secondary'   => '#111827',
        'accent'      => '#F59E0B',
    ],
    'auto-dark' => [
        'name'        => 'Auto Dark',
        'family'      => 'Automobile',
        'description' => 'Header charbon et orange — ateliers mécaniques et tuning.',
        'plan_min'    => 'pro',
        'primary'     => '#111827',
        'secondary'   => '#030712',
        'accent'      => '#F97316',
    ],
    'auto-hero' => [
        'name'        => 'Auto Hero',
        'family'      => 'Automobile',
        'description' => 'Héro rouge brique — vente VO, location de voitures.',
        'plan_min'    => 'pro',
        'primary'     => '#7C2D12',
        'secondary'   => '#5A1F0D',
        'accent'      => '#F97316',
    ],
    'auto-premium' => [
        'name'        => 'Auto Premium',
        'family'      => 'Automobile',
        'description' => 'Luxe noir et or — véhicules de luxe et supercars.',
        'plan_min'    => 'enterprise',
        'primary'     => '#0A0A0A',
        'secondary'   => '#050505',
        'accent'      => '#C9922A',
    ],

    // ══════════════════════════════════════════════════════════════════════
    // ── ARTISAN / PME (4) ─────────────────────────────────────────────────
    // ══════════════════════════════════════════════════════════════════════
    'artisan-classic' => [
        'name'        => 'Artisan Classic',
        'family'      => 'Artisan',
        'description' => 'Terre ocre et ambre — artisans, menuisiers, plombiers, électriciens.',
        'plan_min'    => 'starter',
        'primary'     => '#92400E',
        'secondary'   => '#78350F',
        'accent'      => '#D97706',
    ],
    'artisan-minimal' => [
        'name'        => 'Artisan Minimal',
        'family'      => 'Artisan',
        'description' => 'Ardoise et indigo — artisans modernes et micro-entreprises.',
        'plan_min'    => 'starter',
        'primary'     => '#374151',
        'secondary'   => '#1F2937',
        'accent'      => '#6366F1',
    ],
    'artisan-hero' => [
        'name'        => 'Artisan Hero',
        'family'      => 'Artisan',
        'description' => 'Héro brique — entrepreneurs indépendants et artisans de force.',
        'plan_min'    => 'starter',
        'primary'     => '#7C2D12',
        'secondary'   => '#5A1F0D',
        'accent'      => '#F97316',
    ],
    'artisan-sidebar' => [
        'name'        => 'Artisan Sidebar',
        'family'      => 'Artisan',
        'description' => 'Bande latérale charbon — ateliers et petites entreprises créatives.',
        'plan_min'    => 'pro',
        'primary'     => '#1C1917',
        'secondary'   => '#0C0A09',
        'accent'      => '#F59E0B',
    ],

];
